"""
Main constants.
"""

__author__ = 'mikemeko@mit.edu (Michael Mekonnen)'

from gui.constants import CONNECTOR_BOTTOM
from gui.constants import CONNECTOR_LEFT
from gui.constants import CONNECTOR_RIGHT

# colors
ADDER_FILL = '#FFB873'
ADDER_OUTLINE = 'black'
DELAY_FILL = '#FFB873'
DELAY_OUTLINE = 'black'
GAIN_FILL = '#FFB873'
GAIN_OUTLINE = 'black'
IO_FILL = '#FFB873'
IO_OUTLINE = 'black'
RUN_OUTLINE = 'black'
RUN_RECT_FILL = 'white'
RUN_TRIANGLE_FILL = 'green'

# connector flags for drawable components
ADDER_CONNECTORS = CONNECTOR_BOTTOM | CONNECTOR_LEFT | CONNECTOR_RIGHT
DELAY_CONNECTORS = CONNECTOR_LEFT | CONNECTOR_RIGHT
GAIN_CONNECTORS = CONNECTOR_LEFT | CONNECTOR_RIGHT
X_CONNECTORS = CONNECTOR_RIGHT
Y_CONNECTORS = CONNECTOR_LEFT

# drawable component constants
ADDER_RADIUS = 10
ADDER_SEGMENT_SIZE = 10
DELAY_SIZE = 40
GAIN_LEFT_VERTICES = (0, 20, 40, 0, 40, 40)
GAIN_RIGHT_VERTICES = (0, 0, 0, 40, 40, 20)
IO_SIZE = 40
IO_PADDING = 40
RUN_RECT_SIZE = 40
RUN_TRIANGLE_VERTICES = (10, 10, 10, 30, 30, 20)

# text
DELAY_TEXT = 'R'
