"""
Constants.
"""

__author__ = 'mikemeko@mit.edu (Michael Mekonnen)'

# drawing board constants
CONNECTOR_BOTTOM = 2**2
CONNECTOR_LEFT =   2**3
CONNECTOR_RIGHT =  2**1
CONNECTOR_TOP =    2**0
CONNECTOR_COLOR = 'grey'
CONNECTOR_RADIUS = 4
CONNECTOR_TAG = 'connector_tag'
DRAG_TAG = 'drag_tag'
DRAWING_BOARD_BACKGROUND_COLOR = 'white'
DRAWING_BOARD_HEIGHT = 400
DRAWING_BOARD_MARKER_COLOR = 'grey'
DRAWING_BOARD_MARKER_SEPARATION = 10
DRAWING_BOARD_MARKER_RADIUS = 1
DRAWING_BOARD_WIDHT = 600
